import React from 'react';
import {supabase} from './supabase';
import './styles.css';
const money=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2});
export default function App(){
 const [tab,setTab]=React.useState('dashboard'),[products,setProducts]=React.useState([]),[loading,setLoading]=React.useState(true),[error,setError]=React.useState(''),[name,setName]=React.useState(''),[price,setPrice]=React.useState(''),[stock,setStock]=React.useState('');
 const load=React.useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from('products').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else{setError('');setProducts(data||[])}setLoading(false)},[]);
 React.useEffect(()=>{load()},[load]);
 async function add(e){e.preventDefault();if(!name||Number(price)<0)return;const {error}=await supabase.from('products').insert({name,sale_price:Number(price),cost_price:0,stock:Number(stock)||0,minimum_stock:0});if(error)setError(error.message);else{name&&setName('');setPrice('');setStock('');load()}}
 async function remove(id){if(!confirm('Delete this product?'))return;const {error}=await supabase.from('products').delete().eq('id',id);if(error)setError(error.message);else load()}
 return <div className="app"><aside><div className="brand"><span>ي</span><div><b>يارا</b><small>نظام المصنع</small></div></div>{[['dashboard','الرئيسية','⌂'],['products','المنتجات والمخزون','▦'],['sales','نقطة البيع','＋'],['cash','الخزنة','▣'],['reports','التقارير','▤']].map(([id,label,icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><i>{icon}</i>{label}</button>)}<div className="sidefoot">متصل بـ Supabase<br/><small>البيانات محفوظة أونلاين</small></div></aside><main><header><div><h1>{tab==='dashboard'?'صباح الخير 👋':tab==='products'?'المنتجات والمخزون':tab==='sales'?'نقطة البيع':tab==='cash'?'الخزنة':'التقارير'}</h1><p>{new Date().toLocaleDateString('ar-EG',{weekday:'long',year:'numeric',month:'long',day:'numeric'})}</p></div><button className="refresh" onClick={load}>↻ تحديث</button></header>{error&&<div className="error">{error}</div>}{tab==='dashboard'&&<><section className="hero"><div><span>لوحة التحكم</span><h2>إدارة مصنعك<br/><em>بوضوح وهدوء.</em></h2><p>تابع المبيعات والمخزون والخزنة من مكان واحد.</p></div><div className="heroMark">ي</div></section><div className="stats"><div><small>عدد المنتجات</small><strong>{products.length}</strong><em>صنف مسجل</em></div><div><small>إجمالي المخزون</small><strong>{money(products.reduce((a,p)=>a+Number(p.stock||0),0))}</strong><em>وحدة</em></div><div><small>أصناف منخفضة</small><strong>{products.filter(p=>Number(p.stock||0)<=Number(p.minimum_stock||0)).length}</strong><em>تحتاج مراجعة</em></div></div><section className="panel"><div className="panelhead"><h3>آخر المنتجات</h3><button onClick={()=>setTab('products')}>عرض الكل ←</button></div><ProductTable products={products.slice(0,5)} remove={remove} loading={loading}/></section></>}{tab==='products'&&<section className="panel products"><div className="panelhead"><h3>إدارة المنتجات</h3></div><form className="addform" onSubmit={add}><input placeholder="اسم المنتج" value={name} onChange={e=>setName(e.target.value)}/><input type="number" min="0" placeholder="سعر البيع" value={price} onChange={e=>setPrice(e.target.value)}/><input type="number" min="0" placeholder="الكمية" value={stock} onChange={e=>setStock(e.target.value)}/><button>+ إضافة منتج</button></form><ProductTable products={products} remove={remove} loading={loading}/></section>}{tab==='sales'&&<Empty title="نقطة البيع" text="شاشة البيع جاهزة للربط بالفواتير والمنتجات في الخطوة التالية."/>}{tab==='cash'&&<Empty title="الخزنة" text="حسابات الكاش وفودافون كاش وإنستا باي ستتصل بجدول الخزائن."/>}{tab==='reports'&&<Empty title="التقارير" text="التقارير ستُبنى على بيانات المبيعات والإنتاج بعد إدخال أول فاتورة."/>}</main></div>}
function ProductTable({products,remove,loading}){return <div className="tablewrap">{loading?<div className="empty">جاري تحميل البيانات...</div>:products.length===0?<div className="empty">لا توجد منتجات حتى الآن. أضف أول منتج من صفحة المنتجات.</div>:<table><thead><tr><th>المنتج</th><th>سعر البيع</th><th>المخزون</th><th>الحالة</th><th></th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.sku||'بدون كود'}</small></td><td>{money(p.sale_price)} ج.م</td><td>{money(p.stock)}</td><td><span className={Number(p.stock)<=Number(p.minimum_stock)?'pill low':'pill'}>{Number(p.stock)<=Number(p.minimum_stock)?'منخفض':'متوفر'}</span></td><td><button className="delete" onClick={()=>remove(p.id)}>حذف</button></td></tr>)}</tbody></table>}</div>}
function Empty({title,text}){return <section className="emptyPage"><div className="bigicon">✦</div><h2>{title}</h2><p>{text}</p><span>سنكملها على نفس النظام، بدون إعادة بناء المشروع.</span></section>}
